// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whwwxbjspdvpdgofsjkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indod3d4YmpzcGR2cGRnb2Zzamt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyNzE1ODUsImV4cCI6MjA3Nzg0NzU4NX0.ZsAdIQr5sivoD46QlgKeo1cbfV0EQDzMZjdLNjvWXaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});